version: "3.4"
services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - "27017:27017"
        networks:
            - dockernosql-network
        volumes:
            - "./docker-mongodb-volume:/data/db"
    mongo-express:
        image: mongo-express
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
        depends_on:
            - mongo
        networks:
            - dockernosql-network
    app:
        build: .
        restart: always
        networks:
            - dockernosql-network

networks:
    dockernosql-network:
        driver: bridge
